export const FETCH_PREVISAO = 'FETCH_PREVISAO';
export const FETCH_PREVISAO_SUCCESS = 'FETCH_PREVISAO_SUCCESS';
export const FETCH_PREVISAO_FAIL = 'FETCH_PREVISAO_FAIL';

export const FETCH_PREVISAO_USUARIO_LOGADO = 'FETCH_PREVISAO_USUARIO_LOGADO';
export const FETCH_PREVISAO_USUARIO_LOGADO_SUCCEES =
  'FETCH_PREVISAO_USUARIO_LOGADO_SUCCEES';

export const FETCH_PREVISAO_USUARIO_LOGADO_FAIL =
  'FETCH_PREVISAO_USUARIO_LOGADO_FAIL';
