export const FORECAST = [
  { id: 0, titulo: 'Tempestade forte' },
  { id: 1, titulo: ' Tempestade tropical' },
  { id: 2, titulo: 'Furacão' },
  { id: 3, titulo: 'Tempestades severas' },
  { id: 4, titulo: 'Tempestades' },
  { id: 5, titulo: 'Misto de neve e chuva' },
  { id: 6, titulo: 'Misto chuva e gelo' },
  { id: 7, titulo: 'Misto neve e gelo' },
  { id: 8, titulo: 'Geada fina' },
  { id: 9, titulo: 'Chuviscos' },
  { id: 10, titulo: 'Congelamento chuva' },
  { id: 11, titulo: 'Alguns chuviscos' },
  { id: 12, titulo: 'Neve baixa' },
  { id: 13, titulo: 'Tempestade com neve' },
  { id: 14, titulo: 'Ventania com neve' },
  { id: 15, titulo: 'Neve' },
  { id: 16, titulo: 'Granizo' },
  { id: 17, titulo: 'Gelo' },
  { id: 18, titulo: 'Poeira' },
  { id: 19, titulo: 'Neblina' },
  { id: 20, titulo: 'Tempestade de areia' },
  { id: 21, titulo: 'Fumacento' },
  { id: 22, titulo: 'Vento acentuado' },
  { id: 23, titulo: 'Ventania' },
  { id: 24, titulo: 'Tempo frio' },
  { id: 25, titulo: 'Tempo nublado' },
  { id: 26, titulo: 'Parcialmente nublado' },
  { id: 27, titulo: 'Tempo limpo' },
  { id: 28, titulo: 'Ensolarado' },
  { id: 29, titulo: 'Estrelado' },
  { id: 30, titulo: 'Ensolarado com muitas nuvens' },
  { id: 31, titulo: 'Misto chuva e granizo' },
  { id: 32, titulo: 'Ar quente' },
  { id: 33, titulo: 'Tempestades isoladas' },
  { id: 34, titulo: 'Trovoadas dispersas' },
  { id: 35, titulo: 'Chuvas esparsas' },
  { id: 36, titulo: 'Pesados neve' },
  { id: 37, titulo: 'Chuviscos com neve' },
  { id: 38, titulo: 'Neve pesada' },
  { id: 39, titulo: 'Sol com poucas nuvens' },
  { id: 40, titulo: 'Chuva' },
  { id: 41, titulo: 'Queda de neve' },
  { id: 42, titulo: 'Serviço não disponível' },
];

export const CONDITONS = [
  { titulo: 'storm', descrição: 'tempestade' },
  { titulo: 'snow', descricao: 'neve' },
  { titulo: 'hail', descricao: 'granizo' },
  { tituluo: 'rain', descricao: 'chuva' },
  { titulo: 'fog', descricao: 'neblina' },
  { titulo: 'clear_day', descricao: 'dia limpo' },
  { titulo: 'clear_night', descricao: 'noite limpa' },
  { titulo: 'cloud', descricao: 'nublado' },
  { titulo: 'cloudly_day', descricao: 'nublado de dia' },
  { titulo: 'cloudly_night', descricao: 'nublado de noite' },
  { titulo: 'none_day', descricao: 'erro ao obter mas está de dia' },
  { titulo: 'none_night', descricao: 'erro ao obter mas está de noite' },
];
