export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAIL = 'FETCH_LOGIN_FAIL';

export const FETCH_NEW_USER = 'FETCH_NEW_USER';
export const FETCH_NEW_USER_SUCCESS = 'FETCH_NEW_USER_SUCCESS';
export const FETCH_NEW_USER_FAIL = 'FETCH_NEW_USER_FAIL';
