export const FETCH_VERIFY_SESSION = 'FETCH_VERIFY_SESSION';
export const FETCH_VERIFY_SESSION_SUCCESS = 'FETCH_VERIFY_SESSION_SUCCESS';
export const FETCH_VERIFY_SESSION_FAIL = 'FETCH_VERIFY_SESSION_FAIL';
